config/routes.rb
Rails.application.routes.draw do
  resources :instructions
  resources :recipes
  resources :ingredients
  resources :quantities
  resources :measurements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  has_many :recipe_instructions
  has_many :recipe, through: :recipe_instructions
  accepts_nested_attributes_for :recipe_instructions

  attr_accessor :order
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: %i[ show edit update destroy ]

  # GET /instructions or /instructions.json
  def index
    @instructions = Instruction.all
  end

  # GET /instructions/1 or /instructions/1.json
  def show
  end

  # GET /instructions/new
  def new
    @instruction = Instruction.new
  end

  # GET /instructions/1/edit
  def edit
  end

  # POST /instructions or /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to @instruction, notice: "Instruction was successfully created." }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1 or /instructions/1.json
  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: "Instruction was successfully updated." }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1 or /instructions/1.json
  def destroy
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to instructions_url, notice: "Instruction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instruction_params
      params.require(:instruction).permit(:short_hand_name, :description, :time_amount)
    end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/_form.html.erb
<%= form_with(model: instruction, local: true) do |form| %>
  <% if instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% instruction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :short_hand_name %>
    <%= form.text_field :short_hand_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :time_amount %>
    <%= form.number_field :time_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructions/edit.html.erb
<h1>Editing Instruction</h1>

<%= render 'form', instruction: @instruction %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructions</h1>

<table>
  <thead>
    <tr>
      <th>Short hand name</th>
      <th>Description</th>
      <th>Time acount</th>
      <th>Time amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructions.each do |instruction| %>
      <tr>
        <td><%= instruction.short_hand_name %></td>
        <td><%= instruction.description %></td>
        <td><%= instruction.time_amount %></td>
        <td><%= link_to 'Show', instruction %></td>
        <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
        <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instruction', new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New Instruction</h1>

<%= render 'form', instruction: @instruction %>

<%= link_to 'Back', instructions_path %>

app/views/instructions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short hand name:</strong>
  <%= @instruction.short_hand_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @instruction.description %>
</p>

<p>

<p>
  <strong>Time amount:</strong>
  <%= @instruction.time_amount %>
</p>

<%= link_to 'Edit', edit_instruction_path(@instruction) %> |
<%= link_to 'Back', instructions_path %>