config/routes.rb
Rails.application.routes.draw do
  resources :instructions
  resources :recipes
  resources :ingredients
  resources :quantities
  resources :measurements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_instructions
  has_many :instructions, through: :recipe_instructions

  accepts_nested_attributes_for :instructions, allow_destroy: true
  accepts_nested_attributes_for :recipe_instructions
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  accepts_nested_attributes_for :recipe_ingredients

  def ingredients
    recipe_ingredients
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    render "recipes/edit", locals: {recipe: @recipe, recipe_ingredients: @recipe.recipe_ingredients, recipe_instructions: @recipe.recipe_instructions}
  end

  # POST /recipes or /recipes.json
  def create
    puts "LOUIS RANDALL THE PARAMS FIRST IN CREATE ARE: #{recipe_params.inspect}"
    puts "LOUIS RANDALL THE INSTRUCTIONS: #{params["Instruction"]}"

    instruction_params = {}
    ingredient_params = {}
    updated_params = recipe_params
    puts "louis randall the updated_params first look: #{updated_params.inspect}"
    puts "louis randall the updated_params first look new instructions: #{updated_params["New Instructions"]}"

    if params["Ingredient"].present?
      params["Ingredient"].each_with_index do |id, index|
        ingredient_params[id] = [id, params["Quantity"][index].to_d, params["Measurement"][index]]
      end
    end

    if params["Instruction"].present?
      order_instructions = params["Order"].map(&:to_i)
      params["Instruction"].each_with_index do |id, index|
        puts "louis randall the order params: #{params['Order']}"
        instruction_params["#{id} - #{index}"] = [id, order_instructions[index]]
      end
    end

    puts "LOUIS RANDALL THE INSTRUCTION PARAMS: #{params["instructions_attributes"]}"
    puts "LOUIS RANDALL THE UPDATED INSTRUCTION PARAMS: #{instruction_params}"
    instructions_attributes = updated_params["New Instructions"]
    puts "LOUIS RANDALL NEW INSTRUCTIONS FOR YOU: #{instructions_attributes}"

    updated_params.delete("Instruction")
    updated_params.delete("Ingredient")
    updated_params.delete("Quantity")
    updated_params.delete("Measurement")
    puts "LOUIS RANDALL AND NOW THE PARAMS ARE: #{updated_params}"

    puts "LOUIS RANDALL THE DELETE:: #{updated_params.delete("New Instructions")}"


    puts "LOUIS RANDALL AND NOW THE PARAMS ARE: #{updated_params}"
    puts "LOUIS RANDALL THE INGREDIENT PARAMS: #{ingredient_params}"
    @recipe = Recipe.new(updated_params)

    puts "LOUIS RANDALL THE RECIPE: #{@recipe.inspect}"
    respond_to do |format|
      if @recipe.save! && recipe_ingredient_creation(@recipe, ingredient_params) && recipe_instruction_creation(@recipe,instruction_params ) && create_new_instructions(@recipe, instructions_attributes)
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    updated_params = recipe_params
    puts "LOUIS RANDALL THE PARAMS: #{params.inspect}"

    updated_params.delete("Instruction")
    updated_params.delete("Ingredient")
    updated_params.delete("Quantity")
    updated_params.delete("Measurement")
    updated_params.delete("instructions_attributes")

    respond_to do |format|
      if @recipe.update(updated_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      puts "LOUIS RANDALL LOOK AT THE PARAMS: #{params.inspect}"
      params["recipe"]["Ingredient"] = params["Ingredient"]
      puts "LOUIS RANDALL LOOK AT THE PARAMS: #{params.inspect}"
      puts "LOUIS RANDALL THE INSTRUCTION PARAMS: #{params["instructions_attributes"]}"
      puts "LOUIS RANDALL THE INSTRUCTION PARAMS: #{params[:instructions_attributes]}"

      params.require(:recipe).permit(:name, :description, :expert, :image_ur, :Ingredient, :Quantity, :Measurement, :instructions_attributes, ingredient_attributes: [:id, :name, :_destroy], ingredients_attributes: [:id, :name, :_destroy]).merge({"Ingredient": params["Ingredient"]}).merge({"Quantity": params["Quantity"]}).merge({"Instruction": params["Instruction"]}).merge({"New Instructions": params['recipe']['instructions_attributes']})
    end

  def recipe_ingredient_creation(recipe, ingredient_params)
    ingredient_params.each do |key, value|
      puts "LOUIS RANDALL VALUE: #{value.inspect}"
      recipe.recipe_ingredients.find_or_create_by(ingredient_id: value[0], quantity_id:value[1], measurement_id: value[2])
    end
  end

  def recipe_instruction_creation(recipe, instruction_params)
    puts "LOUIS RANDALL instruction_params: #{instruction_params}"
    instruction_params.each do |key, value|
      puts "LOUIS RANDALL THE VALUE "
      recipe.recipe_instructions.find_or_create_by(instruction_id: value[0], order: value[1])
    end
  end

  def create_new_instructions(recipe, instructions_attributes)
    recipe = recipe
    puts "LOUIS RANDALL TEH create_new_instructions: #{instructions_attributes}"
    instructions_attributes.each do |k, v|
      attr = v
      attr["time_amount"] = v["time_amount"].to_i
      puts "LOUIS RANDALL TEH V: #{v.inspect}"
      puts "LOUIS RANDALL TEH V: #{v.inspect}"

      instruction = Instruction.new(short_hand_name: attr["short_hand_name"], description: attr["description"], time_amount: attr["time_amount"])
      recipe.recipe_instructions.find_or_create_by(instruction: instruction, order: attr["order"])
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true, dynamic: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :expert %>
    <%= form.check_box :expert %>
  </div>

  <div class="field">
    <%= form.label :image_ur %>
    <%= form.text_area :image_ur %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :ingredients %>
    <%#= form.collection_select(:recipe, :ingredients, Ingredient.all, :id) %>
<!--  </div>-->

  <div class="field">
    <div class="ingredients">
      <%= form.fields_for :ingredients, recipe.ingredients.build, dynamic: true do |ff| %>
        <%= render partial: "ingredient_fields", locals: { f: ff, l: form, recipe: :recipe, build_instruction: true }  %>
        <%=puts "LOUIS RANDALL THE PARAMS: #{params.inspect}" %>
      <% end %>
    </div>

    <%= link_to_remove_association "Delete", form, data: { association_insertion_node: '.ingredients'}%>
    <%= link_to_add_association "Add Ingredient", form, :ingredients, render_options: {locals: { l: form, build_instruction: true }}, data: { association_insertion_node: '.ingredients', association_insertion_method: :append } %>
  </div>

  <div class="field">
    <div class="instructions">
      <%= form.fields_for :instructions, recipe.instructions.build, dynamic: true do |ff| %>
        <%= render partial: "instruction_fields", locals: { f: ff, l: form, recipe: :recipe, build_instruction: false }  %>
        <%=puts "LOUIS RANDALL THE PARAMS: #{params.inspect}" %>
      <% end %>
    </div>

    <%= link_to_remove_association "Delete", form, data: { association_insertion_node: '.instructions'}%>
    <%= link_to_add_association "Add Instruction", form, :instructions, render_options: {locals: { l: form, build_instruction: false }}, data: { association_insertion_node: '.instructions', association_insertion_method: :append } %>
  </div>

  <div class="field">
    <div class="build_instructions">
    </div>

    <%= link_to_remove_association "Delete", form, data: { association_insertion_node: '.build_instructions'}%>
    <%= link_to_add_association "Add Instruction from Scratch", form, :instructions, render_options: {locals: { l: form, build_instruction: true }}, data: { association_insertion_node: '.build_instructions', association_insertion_method: :append } %>
  </div>

<!--  <div class="field">-->
    <%#= fields_for :ingredient, @recipe.ingredients do |i| %>
      <%#= i.label "Ingredient" %>
      <%#= i.collection_select(:recipe, :ingredients, Ingredient.all, :id) %>
    <%# end %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
    <%=puts "LOUIS RANDALL THE PARAMS: #{params.inspect}" %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="field">
  <%= f.label "Ingredients name" %>

      <%= puts "louis randall the params for the ingredients from the edit side: #{params.inspect}" %>
      <%= select_tag 'Ingredient', options_for_select(Ingredient.all.collect{ |u| [u.name, u.id.to_s]}), include_blank: true, multiple: true %>
      <%= select_tag 'Quantity', options_for_select(Quantity.all.collect{ |u| [u.amount, u.id.to_s]}), include_blank: true, multiple: true %>
      <%= select_tag 'Measurement', options_for_select(Measurement.all.collect{ |u| [u.name, u.id.to_s]}), include_blank: true, multiple: true %>

  <%#= l.collection_select(:ingredient, Ingredient.all, :id, :name, {}, {:multiple => true, :size => 0}) %>
  <%#= l.select :ingredients, Ingredient.all.collect(&:name), {include_blank: true}, { multiple: true} %>


</div>

app/views/recipes/_instruction_fields.html.erb
<div class="field">
  <%#= l.collection_select(:ingredient, Ingredient.all, :id, :name, {}, {:multiple => true, :size => 0}) %>
  <%#= l.select :ingredients, Ingredient.all.collect(&:name), {include_blank: true}, { multiple: true} %>

  <% if build_instruction == true %>
    <div>
      <div class="field">
        <%= f.label "Instruction name" %>
        <%= f.text_field :short_hand_name %>
      </div>

      <div class="field">
        <%= f.label "Instruction description" %>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label "Instruction time amount" %>
        <%= f.number_field :time_amount %>
      </div>

      <div class="field">
        <%= f.label "Step Order in Recipe" %>
        <%= f.number_field :order %>
      </div>
    </div>
  <% else %>
    <div>
      <%= f.label "Instruction name and order" %>
      <%= select_tag 'Instruction', options_for_select(Instruction.all.collect{ |u| [u.short_hand_name, u.id.to_s]}), include_blank: true, multiple: true %>
      <%= select_tag 'Order', options_for_select(1..100), include_blank: true, multiple: true %>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= form_with(model: @recipe, local: true, dynamic: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :expert %>
    <%= form.check_box :expert %>
  </div>

  <div class="field">
    <%= form.label :image_ur %>
    <%= form.text_area :image_ur %>
  </div>

  <div class="field">
    <%= form.label :image_ur %>
    <%= form.text_area :image_ur %>
  </div>

  <% if params['action'] == 'edit' %>
    <div class="field">
      <div class="ingredients">
        <% form_for @recipe.recipe_ingredients do |ff| %>
          <%= ff.label :ingredient_id %>
          <%= ff.number_field :ingredient_id %>
        <% end  %>
        <%= render partial: "ingredient_fields", locals: { f: form, recipe: @recipe }  %>
      </div>

      <%= link_to_remove_association "Delete", form, data: { association_insertion_node: '.ingredients'}%>
      <%= link_to_add_association "Add Ingredient", form, :ingredients, render_options: {locals: { f: form, recipe: @recipe }}, data: { association_insertion_node: '.ingredients', association_insertion_method: :append } %>
    </div>
  <% else %>
    <div class="field">
      <div class="ingredients">
        <%= form.fields_for :ingredients, @recipe.recipe_ingredients, dynamic: true do |ff| %>
          <%= render partial: "ingredient_fields", locals: { f: ff, l: form, recipe: :recipe }  %>
          <%=puts "LOUIS RANDALL THE cool PARAMS: #{params.inspect}" %>
        <% end %>
      </div>

      <%= link_to_remove_association "Delete", form, data: { association_insertion_node: '.ingredients'}%>
      <%= link_to_add_association "Add Ingredient", form, :ingredients, render_options: {locals: { l: form }}, data: { association_insertion_node: '.ingredients', association_insertion_method: :append } %>
    </div>
  <% end %>



  <div class="actions">
    <%= form.submit %>
    <%=puts "LOUIS RANDALL THE PARAMS: #{params.inspect}" %>
  </div>
<% end %>

<%# form_for @recipe.recipe_ingredients, url: {action: "edit"}, method: "patch" do |form| %>
<!--  <div class="field">-->
    <%#= form.label :ingredient_id %>
    <%#= form.integer :ingredient_id %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :measurement_id %>
    <%#= form.integer :measurement_id %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :quantity_id %>
    <%#= form.integer :quantity_id %>
<!--  </div>-->
  <%#= f.submit %>
<%# end %>


<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<br>
<%= link_to 'New Recipe', new_recipe_path %>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Expert</th>
      <th>Image ur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.expert %></td>
        <td><%= recipe.image_ur %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <p>
    <strong>Name:</strong>
    <%= @recipe.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @recipe.description %>
  </p>

  <p>
    <strong>Expert:</strong>
    <%= @recipe.expert %>
  </p>

  <p>
    <strong>Image ur:</strong>
    <%= @recipe.image_ur %>
  </p>
</div>

<br>
<div class="table">
  <h2>Recipe Ingredients</h2>
  <table>
    <tr>
      <th>Ingredient Name</th>
      <th>Quantity</th>
      <th>Measurement Type</th>
    </tr>

    <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
      <tr>
        <td><%= recipe_ingredient.ingredient.name %></td>
        <td><%= recipe_ingredient.quantity.amount %></td>
        <td><%= recipe_ingredient.measurement.name %></td>

      </tr>
    <% end %>
  </table>
</div>

<div class="table">
  <h2>Instructions</h2>
  <table>
    <tr>
      <th>Instruction Name</th>
      <th>Description</th>
      <th>Time Amount (seconds)</th>
    </tr>

    <% @recipe.recipe_instructions.each do |recipe_instruction| %>
      <tr>
        <td><%= recipe_instruction.instruction.short_hand_name %></td>
        <td><%= recipe_instruction.instruction.description %></td>
        <td><%= recipe_instruction.instruction.time_amount %></td>

      </tr>
    <% end %>
  </table>
</div>



<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>